// Generate very short memorable names for anon skills
// Format: 2 letters + noun (e.g., an.cat, xy.fish)

// 2-letter prefixes (common English)
const PREFIXES = [
  'ab', 'ac', 'ad', 'af', 'ag', 'ah', 'aj', 'ak', 'al', 'am', 'an', 'ap', 'ar', 'as', 'at', 'aw',
  'ax', 'ay', 'ba', 'be', 'bi', 'bl', 'bo', 'br', 'bu', 'by', 'ca', 'ce', 'ch', 'cl', 'co', 'cr',
  'cu', 'da', 'de', 'di', 'do', 'dr', 'du', 'dy', 'eb', 'ed', 'ef', 'eh', 'el', 'em', 'en', 'er',
  'es', 'et', 'ex', 'ey', 'fa', 'fe', 'fi', 'fl', 'fo', 'fr', 'fu', 'ga', 'ge', 'gi', 'gl', 'gn',
  'go', 'gr', 'gu', 'ha', 'he', 'hi', 'ho', 'hu', 'hy', 'id', 'if', 'in', 'is', 'it', 'iv', 'ja',
  'je', 'ji', 'jo', 'ju', 'ka', 'ke', 'ki', 'kn', 'ko', 'ky', 'la', 'le', 'li', 'lo', 'lu', 'ma',
  'me', 'mi', 'mo', 'mu', 'my', 'na', 'ne', 'ni', 'no', 'nu', 'ny', 'ob', 'od', 'of', 'oh', 'oi',
  'ok', 'on', 'op', 'or', 'os', 'ow', 'ox', 'oy', 'pa', 'pe', 'pi', 'pl', 'po', 'pr', 'pt', 'pu',
  'ra', 're', 'ri', 'ro', 'ru', 'ry', 'sa', 'sc', 'se', 'sh', 'si', 'sk', 'sl', 'sm', 'sn', 'so',
  'sp', 'st', 'su', 'sy', 'ta', 'te', 'ti', 'to', 'tr', 'tu', 'tw', 'ug', 'uh', 'un', 'up', 'ur',
  'us', 'ut', 'we', 'wi', 'wo', 'xi', 'xu', 'ya', 'ye', 'yi', 'yo', 'za',
];

// Short animal nouns (2-4 letters)
const ANIMALS = [
  'ant', 'ape', 'bat', 'bee', 'bug', 'cat', 'cow', 'crab', 'cub', 'dog', 'doe', 'duck', 'eel',
  'elk', 'emu', 'fly', 'fox', 'frog', 'gull', 'hare', 'hawk', 'hen', 'hog', 'horse', 'hyena',
  'imp', 'jay', 'kid', 'kit', 'koala', 'lion', 'llama', 'lobster', 'lynx', 'mole', 'monkey', 'moose',
  'mouse', 'mule', 'newt', 'owl', 'ox', 'panda', 'parrot', 'penguin', 'pig', 'pigeon', 'pony',
  'quail', 'rabbit', 'ram', 'rat', 'raven', 'seal', 'shark', 'sheep', 'shrew', 'shrimp', 'sloth',
  'snail', 'snake', 'spider', 'squid', 'squirrel', 'swan', 'tapir', 'tiger', 'toad', 'trout',
  'turkey', 'turtle', 'viper', 'vulture', 'walrus', 'wasp', 'weasel', 'whale', 'wolf', 'wombat',
  'woodpecker', 'worm', 'yak', 'zebra',
];

// Short thing nouns (2-4 letters)
const THINGS = [
  'acre', 'arch', 'arm', 'art', 'ash', 'bag', 'ball', 'band', 'bank', 'bar', 'barn', 'base',
  'bath', 'bay', 'beam', 'bean', 'bed', 'bee', 'bell', 'belt', 'bench', 'bike', 'bird', 'blade',
  'boat', 'body', 'bolt', 'bond', 'bone', 'book', 'boom', 'boot', 'bore', 'bowl', 'box', 'brace',
  'brain', 'brake', 'branch', 'brass', 'bread', 'brick', 'bridge', 'brow', 'brush', 'bud', 'bugle',
  'bulb', 'bulk', 'bull', 'bump', 'bundle', 'bureau', 'burn', 'bush', 'bus', 'cab', 'cage', 'cake',
  'calf', 'call', 'calm', 'camp', 'cane', 'cape', 'card', 'cargo', 'carp', 'cart', 'case', 'cash',
  'cast', 'cave', 'cell', 'chain', 'chair', 'chalk', 'chap', 'charm', 'chart', 'chase', 'cheek',
  'cheese', 'chest', 'chick', 'chief', 'child', 'chill', 'chip', 'chop', 'cite', 'city', 'clam',
  'clamp', 'clap', 'claw', 'clay', 'clip', 'cloak', 'clock', 'cloth', 'cloud', 'clown', 'club',
  'clump', 'coach', 'coal', 'coat', 'code', 'coil', 'coin', 'cold', 'collar', 'color', 'comb',
  'cone', 'cook', 'cool', 'cope', 'copy', 'cord', 'core', 'cork', 'corn', 'cost', 'couch', 'cough',
  'count', 'court', 'cover', 'crack', 'cradle', 'craft', 'crane', 'crank', 'crash', 'crate', 'crawl',
  'cream', 'creek', 'crib', 'crop', 'crow', 'cube', 'cuff', 'cup', 'curb', 'cure', 'curl', 'cushion',
  'cycle', 'dado', 'daft', 'damp', 'dare', 'dark', 'dart', 'dash', 'data', 'date', 'dawn', 'dead',
  'deal', 'dean', 'dear', 'debt', 'deck', 'deed', 'deem', 'deep', 'deer', 'desk', 'dial', 'diamond',
  'dick', 'die', 'dime', 'dine', 'ding', 'dinner', 'dip', 'disc', 'dish', 'disk', 'dive', 'dock',
  'dodge', 'doll', 'dollar', 'dome', 'door', 'dose', 'dot', 'dough', 'draft', 'drag', 'drain',
  'drape', 'draw', 'dread', 'dream', 'dress', 'dribble', 'drift', 'drill', 'drink', 'drip', 'drive',
  'drop', 'drum', 'dual', 'duck', 'duct', 'duel', 'duet', 'dull', 'dumb', 'dump', 'dune', 'dunk',
  'dusk', 'dust', 'duty', 'dyed', 'each', 'ear', 'earn', 'ease', 'easel', 'east', 'easy', 'eat',
  'echo', 'edge', 'edit', 'egg', 'ego', 'elbow', 'elder', 'email', 'ember', 'empty', 'end', 'eraser',
  'even', 'ever', 'exam', 'exit', 'extra', 'eye', 'face', 'fact', 'fade', 'fail', 'fair', 'fake',
  'fall', 'fame', 'fan', 'fare', 'farm', 'fast', 'fate', 'fawn', 'fear', 'feast', 'feat', 'fence',
  'fern', 'ferry', 'fetch', 'fever', 'fiber', 'field', 'fiend', 'file', 'fill', 'film', 'filter',
  'filth', 'fin', 'fine', 'finger', 'finish', 'fire', 'firm', 'fish', 'fist', 'flag', 'flair', 'flake',
  'flame', 'flank', 'flare', 'flash', 'flask', 'flat', 'flaw', 'flesh', 'flick', 'flight', 'fling',
  'flip', 'flirt', 'float', 'flock', 'flood', 'floor', 'flour', 'flow', 'flower', 'flu', 'flute',
  'fly', 'foam', 'fog', 'fold', 'folk', 'fond', 'font', 'food', 'fool', 'foot', 'force', 'forge',
  'fork', 'form', 'fort', 'forth', 'forum', 'fossil', 'foul', 'found', 'frame', 'frank', 'fraud',
  'free', 'fresh', 'friend', 'fringe', 'frock', 'frog', 'front', 'frost', 'frown', 'fruit', 'fuel',
  'full', 'fume', 'fund', 'funny', 'fur', 'fuse', 'fuss', 'fuzz', 'gadget', 'gain', 'gait', 'gale',
  'gall', 'game', 'gang', 'gap', 'garage', 'garden', 'gate', 'gauge', 'gavel', 'gaze', 'gear', 'gem',
  'gene', 'gift', 'giggle', 'gild', 'girl', 'give', 'glad', 'gland', 'glare', 'glass', 'glaze',
  'gleam', 'glide', 'glimpse', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'glow', 'glue', 'goal',
  'goat', 'gold', 'golf', 'gone', 'good', 'goose', 'gore', 'gorge', 'gosh', 'gospel', 'grab', 'grace',
  'grade', 'grain', 'gram', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grave', 'gravy',
  'gray', 'graze', 'great', 'greed', 'green', 'greet', 'grid', 'grim', 'grin', 'grind', 'grip',
  'groan', 'groom', 'groove', 'gross', 'group', 'grove', 'grow', 'growl', 'growth', 'gruel', 'gruff',
  'grunt', 'guard', 'guess', 'guest', 'guide', 'guilt', 'guitar', 'gulf', 'gull', 'gulp', 'gum',
  'gun', 'gust', 'gut', 'gutter', 'guy', 'gym', 'habit', 'hack', 'hail', 'hair', 'hale', 'half',
  'hall', 'halo', 'halt', 'ham', 'hammer', 'hand', 'handle', 'hang', 'hank', 'harbor', 'hard',
  'hare', 'harm', 'harp', 'harry', 'harsh', 'harvest', 'hash', 'haste', 'hat', 'hatch', 'hate',
  'haul', 'have', 'haven', 'havoc', 'hawk', 'hazard', 'haze', 'hazel', 'head', 'heal', 'heap',
  'hear', 'heart', 'heat', 'heath', 'heave', 'heavy', 'hedge', 'heel', 'heir', 'heist', 'helium',
  'helix', 'hello', 'helm', 'helmet', 'help', 'hemp', 'herb', 'herd', 'here', 'hero', 'heron',
  'hertz', 'hex', 'hiatus', 'hiccup', 'hide', 'high', 'hike', 'hill', 'hilt', 'hind', 'hint',
  'hippo', 'hire', 'hiss', 'hit', 'hitch', 'hive', 'hoard', 'hobby', 'hock', 'hog', 'hoist',
  'hold', 'hole', 'holiday', 'hollow', 'holster', 'holy', 'home', 'honey', 'honk', 'hood', 'hoof',
  'hook', 'hoop', 'hop', 'hope', 'horn', 'hornet', 'horror', 'horse', 'hose', 'host', 'hour',
  'house', 'hover', 'howl', 'hub', 'huddle', 'hug', 'huge', 'hulk', 'hull', 'hum', 'human', 'humble',
  'humor', 'hump', 'humus', 'hunch', 'hunger', 'hunk', 'hunt', 'hurdle', 'hurl', 'hurt', 'hush',
  'hut', 'hybrid', 'hydra', 'hyena', 'hymn', 'hype', 'ice', 'icing', 'icon', 'idea', 'ideal',
  'idiom', 'idiot', 'igloo', 'ignore', 'ill', 'image', 'imply', 'inch', 'index', 'indie', 'infer',
  'ink', 'inn', 'input', 'iron', 'island', 'issue', 'item', 'ivory', 'jacket', 'jade', 'jaguar',
  'jail', 'jam', 'jar', 'java', 'jazz', 'jean', 'jeep', 'jeer', 'jelly', 'jet', 'job', 'jockey',
  'join', 'joke', 'jolly', 'jolt', 'judge', 'jug', 'juice', 'jump', 'jungle', 'junior', 'junk',
  'jury', 'just', 'kale', 'keen', 'keep', 'keg', 'kelp', 'kept', 'key', 'kick', 'kid', 'kill',
  'kilt', 'kind', 'king', 'kiosk', 'kiss', 'kit', 'kitchen', 'kite', 'kitten', 'kiwi', 'knee',
  'knife', 'knight', 'knit', 'knob', 'knot', 'know', 'koala', 'lack', 'lad', 'ladder', 'lady',
  'lake', 'lamb', 'lamp', 'land', 'lane', 'lap', 'lapse', 'laptop', 'large', 'laser', 'lass',
  'latch', 'late', 'laugh', 'launch', 'laundry', 'law', 'lawn', 'layer', 'lead', 'leaf', 'leak',
  'lean', 'leap', 'learn', 'leather', 'leave', 'lecture', 'led', 'left', 'leg', 'legend', 'lemon',
  'lend', 'lens', 'lent', 'lesson', 'let', 'letter', 'level', 'lever', 'liar', 'lick', 'lie',
  'life', 'lift', 'light', 'like', 'limb', 'lime', 'limit', 'limp', 'line', 'link', 'lion', 'lip',
  'list', 'listen', 'liter', 'litre', 'litter', 'little', 'live', 'liver', 'lizard', 'load',
  'loan', 'lobby', 'local', 'lock', 'lodge', 'loft', 'log', 'logic', 'logo', 'lone', 'long',
  'look', 'loop', 'loose', 'lorry', 'lose', 'loss', 'lost', 'lot', 'lotus', 'loud', 'love',
  'low', 'luck', 'lull', 'lump', 'lung', 'lure', 'lurk', 'lush', 'lust', 'lynx', 'mace', 'machine',
  'mad', 'magazine', 'magic', 'magma', 'mail', 'maim', 'main', 'make', 'male', 'mall', 'mama',
  'mammoth', 'man', 'manage', 'mandate', 'mango', 'manor', 'map', 'maple', 'marble', 'march',
  'mare', 'mark', 'market', 'marriage', 'marsh', 'mask', 'mass', 'mast', 'master', 'mat',
  'match', 'mate', 'math', 'maze', 'meal', 'mean', 'meant', 'meat', 'medal', 'media', 'meet',
  'mellow', 'melon', 'melt', 'member', 'men', 'mend', 'menu', 'merit', 'merry', 'mess', 'message',
  'metal', 'meter', 'method', 'metro', 'micro', 'midst', 'might', 'mild', 'mile', 'milk', 'mill',
  'mimic', 'mind', 'mine', 'mini', 'mint', 'minus', 'minute', 'mirror', 'mirth', 'miser', 'miss',
  'missile', 'mission', 'mist', 'mix', 'moan', 'moat', 'mob', 'mock', 'mode', 'model', 'modem',
  'modern', 'modest', 'module', 'mold', 'mole', 'moment', 'money', 'monitor', 'month', 'mood',
  'moon', 'moor', 'moral', 'more', 'morning', 'mortal', 'moss', 'most', 'moth', 'mother', 'motion',
  'motor', 'motto', 'mound', 'mount', 'mouse', 'mouth', 'move', 'much', 'mud', 'muffin', 'mug',
  'mule', 'multiple', 'mumbo', 'mummy', 'murder', 'muscle', 'museum', 'mushroom', 'music', 'must',
  'mute', 'mutual', 'muzzle', 'myriad', 'myself', 'mystery', 'myth', 'nab', 'nacho', 'nag',
  'nail', 'name', 'nanny', 'nap', 'napkin', 'narration', 'nasal', 'nasty', 'nation', 'nature',
  'near', 'neat', 'neck', 'need', 'needle', 'neglect', 'neighbor', 'neither', 'nerve', 'nest',
  'net', 'network', 'neutral', 'news', 'next', 'nice', 'niche', 'niece', 'night', 'ninja',
  'noble', 'noise', 'nomad', 'noodle', 'noon', 'norm', 'north', 'nose', 'notch', 'note', 'noun',
  'nude', 'numb', 'nurse', 'nut', 'nylon', 'oak', 'oar', 'oasis', 'oat', 'object', 'oblivion',
  'obtain', 'ocean', 'odd', 'ode', 'odor', 'off', 'offer', 'office', 'offset', 'oil', 'okay',
  'old', 'olive', 'omen', 'onion', 'only', 'onset', 'onto', 'open', 'operate', 'opinion', 'opt',
  'optic', 'option', 'opus', 'oral', 'orbit', 'orca', 'orchard', 'order', 'organ', 'orient',
  'origin', 'ornament', 'orphan', 'other', 'otter', 'ought', 'ounce', 'our', 'out', 'outer',
  'output', 'outside', 'oval', 'oven', 'over', 'owner', 'oxide', 'oyster', 'ozone', 'pace',
  'pack', 'packet', 'pact', 'page', 'pagoda', 'paint', 'pair', 'palace', 'pale', 'palm', 'pan',
  'panda', 'pane', 'panel', 'panic', 'papa', 'paper', 'parade', 'parcel', 'park', 'parody',
  'parrot', 'part', 'partner', 'party', 'pass', 'past', 'paste', 'patch', 'path', 'patio',
  'patrol', 'pattern', 'pause', 'pave', 'pawn', 'pay', 'peace', 'peach', 'peak', 'pear', 'pearl',
  'peck', 'peek', 'peel', 'peer', 'pelican', 'pen', 'penalty', 'pendulum', 'penny', 'people',
  'pepper', 'perch', 'peril', 'period', 'permit', 'person', 'pest', 'pet', 'petal', 'petite',
  'phase', 'phone', 'photo', 'piano', 'piece', 'piety', 'pig', 'pike', 'pile', 'pill', 'pillow',
  'pilot', 'pin', 'pine', 'pink', 'pipe', 'pirate', 'pistol', 'pit', 'pitch', 'pizza', 'place',
  'plague', 'plain', 'plan', 'plane', 'planet', 'plant', 'plate', 'play', 'plaza', 'plea',
  'please', 'pledge', 'plot', 'plow', 'pluck', 'plug', 'plum', 'plump', 'plunge', 'plus', 'pocket',
  'poem', 'poet', 'point', 'poison', 'poker', 'pole', 'police', 'polish', 'pond', 'pony', 'pool',
  'poor', 'pop', 'pope', 'porch', 'pork', 'port', 'pose', 'post', 'pot', 'potato', 'potter',
  'pouch', 'pound', 'powder', 'power', 'practice', 'praise', 'pray', 'preach', 'prefer', 'press',
  'prey', 'price', 'pride', 'priest', 'primary', 'print', 'prior', 'prism', 'prison', 'private',
  'prize', 'probe', 'problem', 'proceed', 'process', 'produce', 'product', 'profile', 'profit',
  'program', 'project', 'prom', 'promise', 'proof', 'prophet', 'prose', 'protect', 'protest',
  'proud', 'prove', 'prowl', 'pulse', 'pump', 'punch', 'pupil', 'puppet', 'puppy', 'pure', 'purple',
  'purpose', 'purse', 'push', 'puzzle', 'python', 'quack', 'quake', 'quality', 'quantity',
  'quart', 'queen', 'query', 'quest', 'question', 'quick', 'quiet', 'quilt', 'quirk', 'quota',
  'quote', 'rabbit', 'race', 'rack', 'radar', 'radiance', 'radio', 'raft', 'rage', 'raid',
  'rail', 'rain', 'raise', 'rake', 'rally', 'ramp', 'ranch', 'range', 'rank', 'rapid', 'rare',
  'rat', 'rate', 'ratio', 'rave', 'ray', 'razor', 'reach', 'react', 'read', 'reader', 'real',
  'reality', 'realm', 'reason', 'rebel', 'receipt', 'receive', 'recipe', 'record', 'recover',
  'recruit', 'red', 'reduce', 'reed', 'reef', 'reel', 'refer', 'reflex', 'reform', 'refuge',
  'refuse', 'regal', 'region', 'regret', 'reject', 'relate', 'relief', 'rely', 'remain',
  'remark', 'remedy', 'remember', 'remind', 'remote', 'remove', 'render', 'renew', 'rent',
  'repair', 'repeat', 'repel', 'reply', 'report', 'rescue', 'resent', 'resist', 'resort',
  'resource', 'respect', 'respond', 'rest', 'result', 'retail', 'retain', 'retire', 'return',
  'reveal', 'review', 'revise', 'revive', 'revolt', 'reward', 'rheumatism', 'rhyme', 'rhythm',
  'rib', 'rice', 'rich', 'ride', 'ridge', 'rifle', 'right', 'rigid', 'ring', 'riot', 'ripe',
  'rise', 'risk', 'ritual', 'rival', 'river', 'road', 'roam', 'roar', 'roast', 'robe', 'robot',
  'rock', 'rocket', 'rode', 'role', 'roll', 'roof', 'room', 'root', 'rope', 'rose', 'rosy',
  'rot', 'rotate', 'rotor', 'rough', 'round', 'route', 'royal', 'rub', 'rubber', 'rubbish',
  'rubble', 'ruby', 'rudder', 'rug', 'ruin', 'rule', 'rumor', 'run', 'rung', 'runway', 'rural',
  'rush', 'rust', 'rut', 'sack', 'sad', 'saddle', 'safe', 'sag', 'sail', 'sake', 'salad',
  'sale', 'salt', 'salute', 'same', 'sand', 'sane', 'sash', 'sauce', 'sauna', 'save', 'scan',
  'scandal', 'scare', 'scarf', 'scary', 'scene', 'scent', 'school', 'science', 'scissors',
  'scoff', 'scooter', 'scope', 'score', 'scorn', 'scout', 'scrap', 'screw', 'script', 'scroll',
  'scrub', 'seal', 'search', 'season', 'seat', 'second', 'secret', 'section', 'sector', 'secure',
  'seed', 'seek', 'seem', 'segment', 'seize', 'seldom', 'select', 'self', 'sell', 'semester',
  'senate', 'send', 'senior', 'sensation', 'sense', 'sent', 'separate', 'sequence', 'serial',
  'serious', 'serve', 'session', 'set', 'settle', 'seven', 'severe', 'sew', 'shade', 'shadow',
  'shaft', 'shake', 'shall', 'shallow', 'shame', 'shape', 'share', 'shark', 'sharp', 'shave',
  'shed', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shield', 'shift', 'shine', 'shiny',
  'ship', 'shiver', 'shock', 'shoe', 'shoot', 'shop', 'shore', 'short', 'shot', 'shoulder',
  'shout', 'shove', 'show', 'shower', 'shred', 'shrug', 'shunt', 'shut', 'sick', 'side', 'siege',
  'sight', 'sign', 'signal', 'silence', 'silent', 'silk', 'sill', 'silver', 'simple', 'sin',
  'since', 'sing', 'siren', 'sister', 'site', 'six', 'sixth', 'size', 'skate', 'skeleton', 'sketch',
  'ski', 'skill', 'skin', 'skip', 'skirt', 'skull', 'slab', 'slack', 'slain', 'slam', 'slang',
  'slap', 'slash', 'slate', 'slave', 'sled', 'sleep', 'sleeve', 'slice', 'slide', 'slight',
  'slim', 'sling', 'slip', 'slit', 'slob', 'slop', 'slot', 'slow', 'slum', 'slur', 'smack',
  'small', 'smart', 'smash', 'smear', 'smell', 'smile', 'smoke', 'snack', 'snail', 'snake',
  'snap', 'snare', 'snatch', 'sneak', 'sniff', 'snore', 'snow', 'snug', 'soak', 'soap', 'soar',
  'sob', 'sock', 'soda', 'sofa', 'soft', 'soil', 'solar', 'sold', 'soldier', 'sole', 'solid',
  'solo', 'some', 'son', 'song', 'sonic', 'soon', 'soot', 'sore', 'sort', 'soul', 'sound', 'soup',
  'sour', 'source', 'south', 'space', 'spade', 'spare', 'spark', 'speak', 'spear', 'spec', 'speech',
  'speed', 'spell', 'spend', 'spent', 'sphere', 'spice', 'spider', 'spike', 'spin', 'spine',
  'spiral', 'spirit', 'spit', 'splash', 'split', 'spoil', 'spoke', 'spoon', 'sport', 'spot',
  'spouse', 'spray', 'spread', 'spring', 'squad', 'square', 'squat', 'squid', 'stack',
  'staff', 'stage', 'stain', 'stair', 'stake', 'stale', 'stall', 'stamp', 'stand', 'star',
  'stare', 'stark', 'start', 'stash', 'state', 'station', 'status', 'stay', 'steak', 'steal',
  'steam', 'steel', 'steep', 'steer', 'stem', 'step', 'stereo', 'stick', 'stiff', 'still',
  'sting', 'stink', 'stir', 'stock', 'stole', 'stomach', 'stone', 'stool', 'stop', 'store',
  'storm', 'story', 'stout', 'stove', 'straight', 'strain', 'strand', 'strange', 'strap',
  'straw', 'stray', 'street', 'stress', 'strict', 'stride', 'strife', 'strike', 'string',
  'strip', 'stroke', 'strong', 'struck', 'structure', 'struggle', 'strut', 'stub', 'student',
  'studio', 'study', 'stuff', 'stump', 'stung', 'stunk', 'stunt', 'style', 'subject', 'submit',
  'substance', 'subtle', 'suburb', 'subway', 'succeed', 'success', 'such', 'suck', 'suckle',
  'suds', 'suffer', 'sugar', 'suggest', 'suicide', 'suit', 'suite', 'sulfur', 'sum', 'summit',
  'sun', 'sung', 'sunk', 'super', 'supply', 'support', 'suppose', 'sure', 'surface', 'surge',
  'surprise', 'surround', 'survey', 'survival', 'survive', 'suspect', 'suspend', 'sustain',
  'swallow', 'swamp', 'swan', 'swarm', 'swear', 'sweat', 'sweep', 'sweet', 'swell', 'swept',
  'swift', 'swim', 'swing', 'switch', 'sword', 'symbol', 'symptom', 'syndrome', 'system', 'table',
  'tablet', 'tack', 'tactic', 'tag', 'tail', 'take', 'tale', 'talk', 'tall', 'tame', 'tang',
  'tank', 'tap', 'tape', 'target', 'tariff', 'task', 'taste', 'tattoo', 'taxi', 'tea', 'teach',
  'team', 'tear', 'tech', 'teddy', 'teeth', 'tell', 'temper', 'temple', 'tempo', 'tend', 'tendon',
  'tennis', 'tense', 'tent', 'term', 'test', 'text', 'than', 'thank', 'that', 'thaw', 'theft',
  'theme', 'then', 'there', 'these', 'thick', 'thief', 'thigh', 'thing', 'think', 'third',
  'thirst', 'this', 'thorn', 'those', 'though', 'thought', 'thread', 'threat', 'three',
  'thrill', 'thrive', 'throat', 'throne', 'throw', 'thrust', 'thumb', 'thump', 'thunder',
  'thus', 'ticket', 'tide', 'tie', 'tiger', 'tight', 'tile', 'till', 'tilt', 'time', 'tin',
  'tint', 'tiny', 'tip', 'tissue', 'title', 'toad', 'toast', 'today', 'toe', 'toes', 'toilet',
  'token', 'told', 'toll', 'tomato', 'tomb', 'tomorrow', 'ton', 'tone', 'tongue', 'tonic', 'tonne',
  'tool', 'tooth', 'top', 'torch', 'tornado', 'toss', 'total', 'tour', 'toward', 'tower', 'town',
  'toy', 'trace', 'track', 'trade', 'trail', 'train', 'trait', 'tram', 'transfer', 'trap',
  'trash', 'tray', 'treat', 'tree', 'trek', 'trend', 'trial', 'tribe', 'trick', 'tried',
  'trigger', 'trim', 'trip', 'trophy', 'trouble', 'trousers', 'trout', 'truck', 'true', 'trumpet',
  'trunk', 'trust', 'truth', 'try', 'tube', 'tumor', 'tune', 'tunnel', 'turban', 'turkey',
  'turn', 'turtle', 'tutor', 'tweed', 'twig', 'twilight', 'twin', 'twist', 'type', 'tyrant',
  'ugly', 'ulcer', 'ultra', 'umbrella', 'unable', 'unaware', 'uncle', 'under', 'underwear',
  'unfair', 'unfold', 'unhappy', 'uniform', 'union', 'unique', 'unit', 'universe', 'university',
  'unknown', 'unlock', 'unpack', 'until', 'unusual', 'unveil', 'update', 'upgrade', 'uphold',
  'upon', 'upper', 'upset', 'urban', 'urge', 'usage', 'use', 'used', 'useful', 'useless',
  'user', 'usher', 'usual', 'utility', 'utter', 'vacation', 'vacuum', 'vague', 'vain', 'valley',
  'valuable', 'value', 'valve', 'vampire', 'van', 'vanish', 'variable', 'variety', 'various',
  'vase', 'vast', 'vegetable', 'vehicle', 'vein', 'velvet', 'vendor', 'venom', 'vent', 'venue',
  'verb', 'verdict', 'verse', 'vest', 'vice', 'victim', 'victory', 'video', 'view', 'vigil',
  'vigor', 'vile', 'village', 'vine', 'violin', 'virtual', 'virtue', 'virus', 'visa', 'visit',
  'visual', 'vital', 'vivid', 'vocal', 'vodka', 'voice', 'void', 'volcano', 'volume', 'vote',
  'vowel', 'voyage', 'vulture', 'wade', 'wager', 'wage', 'wagon', 'waist', 'wait', 'wake',
  'walk', 'wall', 'wand', 'want', 'war', 'ward', 'warm', 'warn', 'warp', 'wary', 'wash', 'waste',
  'watch', 'water', 'wave', 'way', 'weak', 'wealth', 'weapon', 'wear', 'weasel', 'weather',
  'web', 'wedding', 'wedge', 'weed', 'week', 'weep', 'weigh', 'weird', 'welcome', 'well',
  'went', 'wept', 'were', 'west', 'wet', 'whale', 'what', 'wheat', 'wheel', 'where', 'which',
  'while', 'whip', 'whisper', 'whistle', 'white', 'whole', 'whom', 'whorl', 'whose', 'widen',
  'widow', 'width', 'wife', 'wild', 'will', 'win', 'wind', 'window', 'wine', 'wing', 'wink',
  'winner', 'winter', 'wire', 'wisdom', 'wise', 'wish', 'wisp', 'witch', 'with', 'witness',
  'wolf', 'woman', 'wonder', 'wood', 'wool', 'word', 'work', 'world', 'worm', 'worn',
  'worried', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'wrap', 'wrapper', 'wreck',
  'wrist', 'write', 'wrong', 'wrote', 'yacht', 'yard', 'yarn', 'yawn', 'year', 'yellow',
  'yesterday', 'yet', 'yield', 'you', 'young', 'your', 'youth', 'zebra', 'zero', 'zest', 'zinc',
  'zone', 'zoom',
];

function randomElement<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Generate very short name: 2 letters + noun (e.g., ancat, xydog)
export function generateAnonName(): string {
  const prefix = randomElement(PREFIXES);
  const noun = randomElement(ANIMALS);
  return `${prefix}${noun}`;
}

// Generate claim token: 3 words + number
export function generateClaimToken(): string {
  const words = [
    'apple', 'brave', 'cloud', 'dream', 'eagle', 'flame', 'grace', 'heart',
    'iris', 'joy', 'king', 'luna', 'magic', 'nova', 'ocean', 'peace', 'quest',
    'rose', 'star', 'tree', 'unity', 'vision', 'wish', 'xenon', 'youth', 'zen',
  ];
  const part1 = randomElement(words);
  const part2 = randomElement(words);
  const num = Math.floor(Math.random() * 1000);
  return `${part1}-${part2}-${num}`;
}